name: Merge Oldest Queue Branch to Main

on:
  schedule:
    - cron: '0 15 * * *'  # 8:00 PM PKT
  workflow_dispatch:

permissions:
  contents: write  # Needed to push and delete branches

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history and all branches

      - name: Check if queue merge is disabled via manual toggle
        id: check_toggle
        env:
          SKIP_QUEUE_MERGE: ${{ vars.SKIP_QUEUE_MERGE }}
        run: |
          echo "SKIP_QUEUE_MERGE is: ${SKIP_QUEUE_MERGE}"
          if [ "$SKIP_QUEUE_MERGE" = "true" ]; then
            echo "Queue merge is disabled via manual toggle. Exiting..."
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Find oldest queue-* branch
        if: steps.check_toggle.outputs.should_skip != 'true'
        id: get_branch
        run: |
          oldest_branch=$(git for-each-ref --sort=committerdate --format='%(refname:short)' refs/remotes/origin/queue-* | head -n 1 || true)
          if [[ -z "$oldest_branch" ]]; then
            echo "No queue-* branches found."
            echo "branch_name=" >> $GITHUB_OUTPUT
          else
            echo "Oldest queue branch: $oldest_branch"
            echo "branch_name=${oldest_branch#origin/}" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config --global user.name "Sohaib-Sana"
          git config --global user.email "dev.sohaibsana@gmail.com"

      - name: Checkout main
        run: |
          git checkout main
          git pull origin main

      - name: Merge oldest queue branch into main
        if: steps.get_branch.outputs.branch_name != ''
        run: |
          git merge origin/${{ steps.get_branch.outputs.branch_name }} --no-edit || echo "Nothing to merge"

      - name: Push changes to main using PAT
        if: steps.get_branch.outputs.branch_name != ''
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sohaib-Sana/taskify.git
          git push origin main

      - name: Delete merged queue branch from origin
        if: steps.get_branch.outputs.branch_name != ''
        run: |
          git push origin --delete ${{ steps.get_branch.outputs.branch_name }}

      - name: Send Telegram notification
        if: steps.get_branch.outputs.branch_name != ''
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Taskify: ✅ Successfully merged '${{ steps.get_branch.outputs.branch_name }}' into 'main' and deleted the branch."
      